#!/usr/bin/python3
from optparse import OptionParser

from ai.src.Client import ClementZappy
from ai.src.Client_Supra import ClientSupra


def parse_arguments():
	usage = "USAGE: ./zappy_ai options arg\n -p\t\t\t\t\tPort\n -n\t\t\t\t\tTeam name\n -m\t\t\t\t\tHostname\n -i\t\t\t\t\tAI id"

	parser = OptionParser(usage)

	parser.add_option("-p", "--port", dest="port", help="Port")
	parser.add_option("-n", "--name", dest="team_name", help="Team name")
	parser.add_option("-m", "--machine", dest="hostname", help="Hostname (default='localhost')", default="localhost")

	(options, _) = parser.parse_args()
	if not options.hostname or not options.port or not options.team_name:
		parser.error("Missing arguments, see usage with -h")
		exit(1)

	return options.hostname, options.port, options.team_name


if __name__ == '__main__':
	hostname, port, team_name = parse_arguments()
	client = ClementZappy(hostname, port, team_name)
	client.run()
